### ISSUE TITLE
Extension doesn't work after latest Overleaf update to file tree

### ISSUE THREAD

**Issue by RobertoGargiulo** [fawind/overleaf-commander#15]

**Comment by fawind** [comment]
Thanks for reporting! Unfortunately, this will continue to happen as Overleaf can change their internal API at will :(

Will take a look during the next couple days, should hopefully be a simple fix!

**Comment by fawind** [comment]
This should be fixed with https://github.com/fawind/overleaf-commander/commit/2dbea1b78e74bed862580dab70a63a637e9030f7 which is part of the 0.1.4 release. The release is currently pending review in the webstore but should hopefully get rolled out soon. 

Closing for now but let me know if you run into any more issue after upgrading!

**Comment by fawind** [comment]
That was fast, 0.1.4 is already published: https://chrome.google.com/webstore/detail/overleaf-commander/bmlefjcamijlejhefedobjohbiekkemb

**Comment by RobertoGargiulo** [comment]
Thanks for the fix! The extension is such a great help
